services:
  service-users:
    build: ./users-service
    ports:
    - "3001:3000"
    restart: always
    environment:
      DB_HOST: users-db
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: usersdb
      DB_PORT: 5432
    depends_on:
      - users-db
    networks: [backend]

  users-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: usersdb
    ports:
      - "5433:5432"
    volumes:
      - users_data:/var/lib/postgresql/data
    networks:
      - backend
  
  service-scheduling:
    build: ./scheduling-service
    restart: always
    environment:
      DB_HOST: scheduling-db
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: schedulingdb
      DB_PORT: 5432
      USERS_API: http://service-users:3000
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - scheduling-db
      - redis
    networks: [backend]

  scheduling-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: schedulingdb
    ports:
      - "5434:5432"
    volumes:
      - scheduling_data:/var/lib/postgresql/data
    networks:
      - backend

  service-notifications:
    build: ./notifications-service
    restart: always
    environment:
      DB_HOST: notifications-db
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: notificationsdb
      DB_PORT: 5432
      USERS_API: http://service-users:3000
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - notifications-db
      - redis
    networks: [backend]

  notifications-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notificationsdb
    ports:
      - "5435:5432"
    volumes:
      - notifications_data:/var/lib/postgresql/data
    networks:
      - backend
    
  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    networks: [backend]
  
  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:8080"
    depends_on:
      - service-users
    networks: [backend]

volumes:
  users_data:
  scheduling_data:
  notifications_data:

networks:
  backend:
    driver: bridge