events {}

http {
  upstream service_users {
    server service-users:3000;
  }

  upstream service_scheduling {
    server service-scheduling:3000;
  }

  upstream service_notifications {
    server service-notifications:3000;
  }

  server {
    listen 8080;

    location /users {
      proxy_pass http://service_users;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /company {
      proxy_pass http://service_users;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /auth/login {
      proxy_pass http://service_users;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /auth/profile {
      proxy_pass http://service_users;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /scheduling {
      proxy_pass http://service_scheduling;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /notifications {
      proxy_pass http://service_notifications;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
  }
}